[project]
name = "datasets"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Admin", email = "xiarimier9006@163.com" }
]
requires-python = ">=3.9"
dependencies = [
    "matplotlib>=3.9.4",
    "numpy>=2.0.2",
]

[project.scripts]
datasets = "datasets:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
